import type { FloatingBlob } from './FloatingBackground';

export const defaultProjectsPageBlobs: FloatingBlob[] = [
  {
    id: 'wave-top-right',
    src: '/images/gradient-wave.webp',
    position: { top: '-8rem', right: '-8rem' },
    size: '24rem',
    blur: 'blur-2xl',
    baseOpacity: 1,
    baseRotate: 12,
    baseScale: 1.5,
  },
  {
    id: 'pink-bottom-left',
    src: '/images/gradient-pink.webp',
    position: { bottom: '-8rem', left: '-8rem' },
    size: '24rem',
    blur: 'blur-xl',
    baseOpacity: 0.8,
    baseRotate: -12,
    baseScale: 1.5,
  },
  {
    id: 'blue-center',
    src: '/images/gradient-blue.webp',
    position: { top: '33%', left: '25%' },
    size: '20rem',
    blur: 'blur-2xl',
    baseOpacity: 0.7,
    baseRotate: 45,
    baseScale: 1.25,
  },
];

export const defaultIntroPageBlobs: FloatingBlob[] = [
  {
    id: 'wave-top-left',
    src: '/images/gradient-wave.webp',
    position: { top: '-5rem', left: '-5rem' },
    size: '24rem',
    blur: 'blur-2xl',
    baseOpacity: 1,
    baseRotate: 12,
    baseScale: 1.5,
  },
  {
    id: 'blue-top-right',
    src: '/images/gradient-blue.webp',
    position: { top: '25%', right: '-8rem' },
    size: '20rem',
    blur: 'blur-xl',
    baseOpacity: 0.85,
    baseRotate: -6,
    baseScale: 1.25,
  },
  {
    id: 'flower-center-left',
    src: '/images/gradient-flower.webp',
    position: { bottom: '25%', left: '25%' },
    size: '18rem',
    blur: 'blur-2xl',
    baseOpacity: 0.7,
    baseRotate: 45,
    baseScale: 1.1,
  },
  {
    id: 'pink-bottom-right',
    src: '/images/gradient-pink.webp',
    position: { bottom: '-5rem', right: '33%' },
    size: '24rem',
    blur: 'blur-xl',
    baseOpacity: 0.85,
    baseRotate: -12,
    baseScale: 1.5,
  },
];

export const defaultHomePageBlobs: FloatingBlob[] = [
  {
    id: 'wave-top-right',
    src: '/images/gradient-wave.webp',
    position: { top: '-10rem', right: '-5rem' },
    size: '28rem',
    blur: 'blur-2xl',
    baseOpacity: 0.5,
    baseRotate: 15,
    baseScale: 1.4,
  },
  {
    id: 'blue-bottom-left',
    src: '/images/gradient-blue.webp',
    position: { bottom: '10%', left: '-8rem' },
    size: '22rem',
    blur: 'blur-2xl',
    baseOpacity: 0.4,
    baseRotate: -20,
    baseScale: 1.3,
  },
  {
    id: 'pink-center-right',
    src: '/images/gradient-pink.webp',
    position: { top: '40%', right: '10%' },
    size: '16rem',
    blur: 'blur-xl',
    baseOpacity: 0.35,
    baseRotate: 30,
    baseScale: 1.2,
  },
];
